<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-ANCCPSQ" failures="1" tests="5" name="SauceDemo Tests" time="78.306" errors="0" timestamp="2025-09-03T09:20:35 IST">
  <testcase classname="tests.LoginTest" name="invalidLoginTest" time="10.522"/>
  <testcase classname="tests.LoginTest" name="validLoginTest" time="9.727"/>
  <testcase classname="tests.AddToCartTest" name="addItemToCartTest" time="6.172"/>
  <testcase classname="tests.CheckoutTest" name="completeCheckoutTest" time="20.687">
    <failure type="java.lang.AssertionError" message="Checkout was not successful expected [THANK YOU FOR YOUR ORDER] but found [Thank you for your order!]">
      <![CDATA[java.lang.AssertionError: Checkout was not successful expected [THANK YOU FOR YOUR ORDER] but found [Thank you for your order!]
at tests.CheckoutTest.completeCheckoutTest(CheckoutTest.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- completeCheckoutTest -->
  <testcase classname="tests.LogoutTest" name="logoutTest" time="4.15"/>
</testsuite> <!-- SauceDemo Tests -->
